### ISSUE TITLE
升级jetcd版本

### ISSUE THREAD

**Issue by wangweicugw** [vtdriverio/vtdriver#2]
测试过程中发现watch时报错，Network closed for unknown reason
https://github.com/etcd-io/jetcd/issues/327

**Comment by Randomyyds** [comment]
0.7.7还是有这个问题

**Comment by wangweicugw** [comment]
> 0.7.7还是有这个问题

是有这个报错么，Network closed for unknown reason 
我记得网络断开就会有这个错误，网络恢复后可以重连上

**Comment by wangweicugw** [comment]
> 0.7.7还是有这个问题

可以提个issue描述下，我们具体看看

**Comment by Randomyyds** [comment]
> > 0.7.7还是有这个问题
> 
> 可以提个issue描述下，我们具体看看

不好意思，我端口搞错了，用2380就报这个

**Comment by wangweicugw** [comment]
> > > 0.7.7还是有这个问题
> > 
> > 
> > 可以提个issue描述下，我们具体看看
> 
> 不好意思，我端口搞错了，用2380就报这个

好的
