### ISSUE TITLE
When using &allowMultiQueries=true, there may be problems when sql is split

### ISSUE THREAD

**Issue by FanChenyu** [vtdriverio/vtdriver#7]
```java
protected List<String> split(String sql) throws SQLException {
        List<String> sqls = new ArrayList<>(Splitter.on(";").omitEmptyStrings().trimResults().splitToList(sql));
        if (sqls.isEmpty()) {
            throw new SQLException("trying to execute empty queries " + sqls);
        }

        return sqls;
    }
```
When sql needs to be split, the method used in VtDriver is similar to sql.split(";"). When ";" exists in comment or value, sql will be split into unexpected results.
Considering the performance loss of using syntax analysis, a tool for splitting SQL can be implemented.

**Comment by xhh1989** [comment]
https://github.com/vtdriverio/vtdriver/blob/main/src/main/java/com/jd/jdbc/vitess/VitessStatement.java#L615
